Mvc/Models/ErrorViewModel.cs
namespace Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mvc/Controllers/FilmController.cs
using Bussiness.Concrete;
using Bussiness.ValidationRules.FluentValidation;
using Core.Aspect.ValidationAspect;
using DataAccess.Concrete.EntityFramework;
using Entity.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace Mvc.Controllers
{
    public class FilmController : Controller
    {
        FilmManager filmManager = new FilmManager(new EfFilmDal());
        public IActionResult Index()
        {

            var values = filmManager.GetList();
            
            return View(values);
        }

        [ValidationAspect(typeof(FilmValidator))]
        [HttpGet]
        public IActionResult Addfilm()
        {
            return View();
        }
    
        [HttpPost]
        public IActionResult Addfilm(Film film)
        {
            if (!ModelState.IsValid)
            {
                return View("Addfilm");
            }
            filmManager.Add(film);
            return RedirectToAction("Index");
        }
  

        public IActionResult Deletefilm(Film film)
        {
            var values = filmManager.GetById(film.Id);
            filmManager.Delete(values);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult FilmDetail(int id)
        {
            var values = filmManager.GetById(id);

            return View(values);
        }
        [HttpPost]
        public IActionResult FilmDetail(Film film)
        {
            filmManager.Update(film);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Search(string p)
        {
            filmManager.Search(p);
            return RedirectToAction("Index");
        }
    }
    
    
}

Mvc/Views/Film/Addfilm.cshtml
@model Entity.Concrete.Film
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Film Kaydet</title>
</head>
<body>
    @using (Html.BeginForm("Addfilm", "Film", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
         <br />
        <label>Film Ad</label><br />
        @Html.TextBoxFor(x=>x.Name)<br />
        @Html.ValidationMessageFor(x => x.Name, "", new { @style = "color:red" })
         <br />
 
        <label>Film Türü</label><br />
        @Html.TextBoxFor(x => x.Genre)<br />
        @Html.ValidationMessageFor(x => x.Genre, "", new { @style = "color:red" })
        <br />
 
        <label>Film Yılı</label><br />
        @Html.TextBoxFor(x => x.Year)<br />
        @Html.ValidationMessageFor(x => x.Year, "", new { @style = "color:red" })
        <br />
 
        <label>Film Salon Numarası</label><br />
        @Html.TextBoxFor(x => x.CinemaId)<br />
        @Html.ValidationMessageFor(x => x.CinemaId, "", new { @style = "color:red" })
         <br />
          <label>Film Yapımcısı</label><br />
         @Html.TextBoxFor(x => x.Director)<br />
        @Html.ValidationMessageFor(x => x.Director, "", new { @style = "color:red" })
     
       <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
    }
</body>
</html>

Mvc/Views/Film/FilmDetail.cshtml
@model Entity.Concrete.Film
@{
    Layout = null;
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <p class="card-description"> Yeni Film Güncelleme Paneli </p>
            <form class="forms-sample" method="post" >
                <div class="form-group">
                    @Html.HiddenFor(x => x.Id)
                    <label>Film Ad</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Film Türü</label>
                    @Html.TextBoxFor(x => x.Genre, new { @class = "form-control" })
                </div>
                <div class="form-group">

                    <label>Yapımcı</label>
                    @Html.TextBoxFor(x => x.Director, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Film Yılı</label>
                    @Html.TextBoxFor(x => x.Year, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Sinema Salon</label>
                    @Html.TextBoxFor(x => x.CinemaId, new { @class = "form-control" })
                </div>

                  <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                <button class="btn btn-dark">İptal</button>
                
            </form>
           
        </div>
    </div>
</div>

Mvc/Views/Film/Index.cshtml
@using Entity.Concrete
@model List<Film>

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Tables - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/startbootstrap-sb-admin-gh-pages/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Start Bootstrap</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->

    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Layouts
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="charts.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Charts
                        </a>
                        <a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <h1 class="mt-4">Tables</h1>
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Tables</li>
                    </ol>
                    <div class="card mb-4">
                    </div>
                    <div class="card mb-4">
                        <div class="card-header">
                            <i class="fas fa-table me-1"></i>
                            <p>FİlMLER</p>
                        </div>
                        <div class="card-body">
                            <table id="datatablesSimple">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Genre</th>
                                        <th>Director</th>
                                        <th>Year</th>
                                        <th>Sil</th>
                                        <th>Güncelle</th>

                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (var x in Model)

                                    {



                                        <tr>
                                            <td>@x.Name</td>
                                            <td>@x.Genre</td>
                                            <td>@x.Director</td>
                                            <td>@x.Year</td>
                                          <td><a action="" href="/Film/Deletefilm/@x.Id" class="btn btn-danger">Sil</a> </td>
                                <td><a href="/Film/FilmDetail/@x.Id" class="btn btn-primary">Detaylar</a> </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <a href="/Film/AddFilm" class="btn btn-primary">Yeni Film Ekle</a>
                        </div>
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2022</div>
                        <div>
                            <a href="#">Enoca Project</a>
                            &middot;
                            <a href="#"></a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/startbootstrap-sb-admin-gh-pages/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/startbootstrap-sb-admin-gh-pages/js/datatables-simple-demo.js"></script>
</body>
</html>

Mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>